# Generated by Django 5.0.7 on 2024-07-27 10:11

import job_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_form_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='resume',
            field=models.FileField(upload_to=job_application.models.unique_upload_to),
        ),
    ]
